### ISSUE TITLE
Potential pathological case where Cache Advance reads no messages for a non-empty file

### ISSUE THREAD

**Issue by bachand** [dfed/CacheAdvance#57] opened 2022-03-09 19:35 UTC
In reviewing https://github.com/dfed/CacheAdvance/pull/52 I read this code again: https://github.com/dfed/CacheAdvance/blob/ed9ece4a186b0073514128a75f1cc401ba4ac130/Sources/CacheAdvance/CacheReader.swift#L45-L51

We bail out of reading messages when we encounter the end of start of the newest message.

I'm wondering if there is a pathologic case where we have a file where the offset of the start of the oldest message (reader offset) equals the offset of the end of the newest message (writer offset).

```
| header | message 4 | message 5 | message 3 | EOF |
```

Let's image a file like above, with no empty space between messages. If there were no empty space between message 5 and message 3, then when someone invoked `message()` I believe we would be in a situation where `startingOffset == offsetInFileAtEndOfNewestMessage`, and we would return no messages. It seems like the current implementation of `messages()` assumes that there will always be some blank space between the end of the oldest message and the start of the newest message when we're in the situation where the messages have "wrapped around."

-----

In writing this issue I wrote a test to I try to verify if this pathological case is real.

```swift
    func test_messagesPathologicalCase() throws {
        let message: TestableMessage = "This is a test"
        let cache = try createCache(sizedToFit: [message, message], overwritesOldMessages: true)
        try cache.append(message: message)
        try cache.append(message: message)
        try cache.append(message: message)

        XCTAssertEqual(try cache.messages().count, 2)
    }
```

I expected this test to fail saying that the count was 0. However, I received this failure instead:

> XCTAssertEqual failed: ("1") is not equal to ("2")

Maybe it's not possible to get into this situation since this code verifies that the writer offset never equals the reader offset.

https://github.com/dfed/CacheAdvance/blob/247011300a7ea874366e49f37cd7412e6236fbbf/Sources/CacheAdvance/CacheAdvance.swift#L225-L226

I decided it was still valuable to post this writeup so I can get confirmation from @dfed that this pathological case is not possible.

**Comment by dfed** [comment] 2022-03-09 22:21
This is indeed a valuable write-up! The line you found in `CacheAdvance.swift` is indeed the line that prevents this pathological case from getting hit. I originally found it via a unit test that I believe is on `main` today. This issue was fixed in https://github.com/dfed/CacheAdvance/pull/40 (specifically in 6a627cf18c98bae83cb4e57ac27a807c980cbf1c), and was [briefly described in our 1.0.1 release tag](https://github.com/dfed/CacheAdvance/releases/tag/1.0.1). Closing since this is fixed.

**Closed by dfed** 2022-03-09 22:21 UTC

**Comment by dfed** [comment] 2022-03-09 22:27
Confirmed that we do have an explicit test on `main` for this case:
https://github.com/dfed/CacheAdvance/blob/ed9ece4a186b0073514128a75f1cc401ba4ac130/Tests/CacheAdvanceTests/CacheAdvanceTests.swift#L267-L306
